name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [ 1, 2 ]
    environment: QA
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '24.x'
    - name: Install dependencies
      run: npm ci
    - name: Start Mokapi
      run: |
          docker run -d --rm --name mokapi -p 80:80 -p 8080:8080 -p 9092:9092 -v ${{ github.workspace }}/mocks:/mocks mokapi/mokapi:latest /mocks
          sleep 5  # Ensure Mokapi is running
    - name: Check Mokapi health
      run: |    
          curl -v http://localhost:8080/health
    - name: Start backend server
      run: nohup node backend/index.js > backend.log 2>&1 &
          echo $! > backend.pid
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test login.spec.ts --shard=${{ matrix.shard }}/2
      env:
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-shard-${{ matrix.shard }}
        path: playwright-report/
        retention-days: 30
    - name: Run Postman Collection
      env:
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      uses: postmanlabs/postman-cli-action@v1
      with:
        command: 'postman app test'
        api-key: ${{ secrets.POSTMAN_API_KEY }}
    - name: Stop Mokapi
      run: docker stop mokapi
    - name: Check backend logs
      run: |
          cat backend.log
    - name: Stop backend server
      run: |
        kill $(cat backend.pid) || true
        
  k6-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1
        with:
          k6-version: 'latest'
          browser: true
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Run K6 tests
        uses: grafana/k6-action@v0.3.1
        with:
          filename: performance/load-test.js
      - uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: ./k6-results.json